BotiqueManagementSystem/urls.py
from django.contrib import admin
from django.urls import path,include
from customers.views import get_all_subscribers
from clothes.views import Add_Clothes,new_clothes_category,get_all_clothes,delete_cloth,edit_clothes
from homepage.views import Display_Admin_Dashboard,get_orders,make_orders_read,delete_orders

urlpatterns = [
    path('d-admin/', admin.site.urls),
    path('', include("homepage.urls")),
    path('customers/', include("customers.urls")),
    path('clothes/', include("clothes.urls")),
    path('admin/clothes/add', Add_Clothes),
    path('admin/clothes/new-category', new_clothes_category),
    path('admin/orders', get_orders),
    path('admin/orders/<int:order_id>', make_orders_read),
    path('admin/orders/<int:order_id>/delete', delete_orders),
    path('admin/clothes/all', get_all_clothes),
    path('admin/clothes/<int:cloth_id>/delete', delete_cloth),
    path('admin/clothes/<int:cloth_id>/edit', edit_clothes),
    path('admin/subscribers', get_all_subscribers),

]

clothes/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from homepage.views import buy_now
from customers.views import add_to_cart,customer_orders
urlpatterns = [
    # path("add",views.Add_Clothes),
    path("",views.get_clothes),
    # path("new-category",views.new_clothes_category),
    path("<int:product_id>/buy",buy_now),
    path("<int:product_id>/add-to-cart",add_to_cart),
    path("<int:product_id>/remove-from-cart",views.remove_from_cart),
    path("<int:product_id>/purchase",customer_orders),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clothes/models.py
from django.db import models

class Clothes_Categories(models.Model):

    class Meta:
        db_table = "Clothes_Categories"

    category_name = models.CharField(max_length=100)



class Clothes(models.Model):
    class Meta:
        db_table = "Clothes"

    name = models.CharField(max_length=200)
    company = models.CharField(max_length=100)
    size = models.CharField(max_length=20)
    price = models.IntegerField()
    color = models.CharField(max_length=20)
    material = models.CharField(max_length=100)
    photo1 = models.FileField(upload_to="cloth_pics")
    photo2 = models.FileField(upload_to="cloth_pics", null=True,blank=True)
    photo3 = models.FileField(upload_to="cloth_pics", null=True,blank=True)
    photo4 = models.FileField(upload_to="cloth_pics", null=True,blank=True)
    photo5 = models.FileField(upload_to="cloth_pics", null=True,blank=True)
    photo6 = models.FileField(upload_to="cloth_pics", null=True,blank=True)
    description = models.TextField()
    category = models.ForeignKey(Clothes_Categories,on_delete=models.CASCADE)

clothes/views.py
from django.shortcuts import render, redirect
from . models import *
from django.contrib import messages
from customers.models import Customer_Clothes,Customer_Cart
from django.db.models import Q
from django.http import HttpResponseRedirect
def Add_Clothes(request):
    orders = Customer_Clothes.objects.filter(is_ordered = False)
    clothes_categories = Clothes_Categories.objects.all()
    if request.method == "POST":
        name = request.POST['name']
        company = request.POST['company']
        size = request.POST['size']
        price = request.POST['price']
        color = request.POST['color']
        material = request.POST['material']
        photo1 = request.FILES['photo1']
        photo2 = request.FILES['photo2']
        photo3 = request.FILES['photo3']
        photo4 = request.FILES['photo4']
        photo5 = request.FILES['photo5']
        photo6 = request.FILES['photo6']
        category = request.POST['cloth_category']
        description = request.POST['description']

        try:
            Clothes.objects.create(
                name = name,
                company = company,
                size = size,
                price = price,
                color = color,
                material = material,
                photo1 = photo1,
                photo2 = photo2 if photo2 else "null",
                photo3 = photo3 if photo3 else "null",
                photo4 = photo4 if photo4 else "null",
                photo5 = photo5 if photo5 else "null",
                photo6 = photo6 if photo6 else "null",
                category_id = category,
                description = description
            )

            messages.success(request,"added")
            return redirect("/admin/clothes/add")
        except Exception as e:
            print(e)
            messages.error(request,"something went wrong!")
            return redirect("/admin/clothes/add")
    return render(request,"add_clothes.html",{"clothes_categories":clothes_categories,"orders_len":orders.count()})


def get_clothes(request):
    orders = Customer_Clothes.objects.filter(is_ordered = False)
    query = 0
    if request.GET.get('query'):
        query = request.GET.get('query')
    clothes = Clothes.objects.all()
    if query:
        clothes = Clothes.objects.filter(Q(name__icontains = query) | Q(company__icontains = query) | Q(material__icontains = query) | Q(category_id__category_name__icontains = query) | Q(price__icontains = query) | Q(color__icontains = query) | Q(size__icontains = query))
        
    return render(request,"user_clothes.html",{"clothes":clothes,"orders_len":orders.count(),"query":query})


def new_clothes_category(request):
    orders = Customer_Clothes.objects.filter(is_ordered = False)
    if request.method == "POST":
        try:
            category = Clothes_Categories.objects.create(
                category_name = request.POST['category_name']
            )
            messages.success(request,"created")
            return redirect("/clothes/new-category")
        except Exception as e:
            print(e)
            messages.error(request,"something went wrong!")
            return redirect("/clothes/new-category")
    return render(request,"add_category.html",{"orders_len":orders.count()})


def get_all_clothes(request):
    if request.user.is_superuser:
        clothes = Clothes.objects.all()
        return render(request,"all_clothes.html",{"clothes":clothes})
    

def delete_cloth(request,cloth_id):
    if request.method == "POST":
        cloth = Clothes.objects.filter(id = cloth_id).delete()
        messages.success(request,"deleted")
        return redirect("/admin/clothes/all")
    

def edit_clothes(request,cloth_id):
    cloth = Clothes.objects.filter(id = cloth_id)
    clothes_categories = Clothes_Categories.objects.all()
    if request.method == "POST":
        name = request.POST['name']
        company = request.POST['company']
        size = request.POST['size']
        price = request.POST['price']
        color = request.POST['color']
        material = request.POST['material']
        photo = request.FILES.get('photo')
        category = request.POST['cloth_category']
        description = request.POST['description']
        print(photo)
        cloth.update(
            name = request.POST['name'] if request.POST['name'] else cloth.first().name, 
            company = company  if request.POST['company'] else cloth.first().company, 
            size = size  if request.POST['size'] else cloth.first().size, 
            price = price  if request.POST['price'] else cloth.first().price, 
            color = color  if request.POST['color'] else cloth.first().color, 
            material = material  if request.POST['material'] else cloth.first().material, 
            photo = photo  if request.FILES.get('photo') else cloth.first().photo, 
            category = category  if request.POST['cloth_category'] else cloth.first().category, 
            description = description  if request.POST['description'] else cloth.first().description, 
        )
        messages.success(request,"updated")
        return redirect(f"/admin/clothes/{cloth_id}/edit")
    return render(request,"edit_clothes.html",{"cloth":cloth.first(),"clothes_categories":clothes_categories})


def remove_from_cart(request,product_id):
    if not(request.user.is_authenticated):
        messages.warning(request,"login required!")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    if request.method == "POST":
        try:
            product = Customer_Cart.objects.filter(product_id = product_id).filter(customer_id = request.user.id).first().delete()
            messages.success(request,"removed from cart")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        except Exception as e:
            print(e)
            messages.error(request,"something went wrong!")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    

clothes/templates/add_category.html
{% extends 'admin.html' %}
{% block contentarea %}

<script>
    document.title = "Add Category";

</script>
<style>
    input {
        max-width: 60%;
        border-radius: 20px !important;
    }
</style>
{%if request.user.is_superuser%}
<div style="width: 100%; display: flex; justify-content: center;">
    <form action="" method="post" style="width: 50%;">
        {%csrf_token%}
        <div class="form-group">
            <label for="">Category Name</label>
            <input type="text" class="form-control" name="category_name" id="id_category_name">
        </div>
        <button class="btn btn-success" style="border-radius: 20px;">Create</button>
    </form>
</div>
<script>
    document.getElementById('new_clothes').classList.remove('btn-primary');
    document.getElementById('new_category').classList.add('btn-primary');
</script>
{%endif%}

{% endblock contentarea %}

clothes/templates/add_clothes.html
{% extends 'admin.html' %}

{% block contentarea %}
{%if request.user.is_superuser%}
<script>
    document.title = "Add Clothes"
</script>
<style>
    input,select,textarea{
        max-width: 60%;
        border-radius: 20px !important;
    }
</style>
<form method="post" enctype="multipart/form-data" style="margin-left: 10%;" >
    {%csrf_token%}
    
        <div style="width:50%;float: left;">
            <div class="form-group">
                <label for="">Suit Name *</label>
                <input type="text" class="form-control" name="name" placeholder="" id="" required>
            </div>
            <div class="form-group">
                <label for="">Manufacturer Name *</label>
                <input type="text" class="form-control" name="company" placeholder="" id="" required>
            </div>
            <div class="form-group">
                <label for="">Size *</label>
                <input type="text" class="form-control" name="size" placeholder="" id="" required>
            </div>
            <div class="form-group">
                <label for="">Pic 1 *</label>
                <input type="file" class="form-control" name="photo1" placeholder="" id="" required>
            </div>
            <div class="form-group">
                <label for="">Pic 2</label>
                <input type="file" class="form-control" name="photo2" placeholder="" id="" >
            </div>
            <div class="form-group">
                <label for="">Pic 3</label>
                <input type="file" class="form-control" name="photo3" placeholder="" id="" >
            </div>
            <div class="form-group">
                <label for="">Pic 6</label>
                <input type="file" class="form-control" name="photo6" placeholder="" id="" >
            </div>
            
            <div class="form-group">
                <label for="">Category *</label>
                <select class="form-control" name="cloth_category" placeholder="" id="" required>
                    {%for category in clothes_categories%}
                    <option value="{{category.id}}">{{category.category_name}}</option>
                    {%endfor%}
                </select>
            </div>
        </div>
        <div style="width: 50%;float: right;">
            <div class="form-group">
                <label for="">Price *</label> (₹)
                <input type="text" class="form-control" name="price" placeholder="" id="" required>
            </div>
            <div class="form-group">
                <label for="">Color *</label>
                <input type="text" class="form-control" name="color" placeholder="" id="" required>
            </div>
            <div class="form-group">
                <label for="">Material *</label>
                <input type="text" class="form-control" name="material" placeholder="" id="" required>
            </div>
            <div class="form-group">
                <label for="">Description *</label>
                <textarea class="form-control" name="description" placeholder="" id="" cols="20" rows="7" required></textarea>
            </div>
            <div class="form-group">
                <label for="">Pic 4</label>
                <input type="file" class="form-control" name="photo4" placeholder="" id="" >
            </div>
            <div class="form-group">
                <label for="">Pic 5</label>
                <input type="file" class="form-control" name="photo5" placeholder="" id="" >
            </div>
            
            
        </div>
        <div style="clear: both;width: 80%;text-align: center;margin-top: 20%;">

            <button class="btn btn-primary" type="subimit">Create</button>
        </div>
        
    </form>
    <script>
        document.getElementById('new_clothes').classList.add('btn-primary');
        document.getElementById('new_category').classList.remove('btn-primary');
    </script>
</div>
{%else%}
<div style="text-align: center;">
    <h2>Error</h2>
</div>
{%endif%}
{% endblock contentarea %}

clothes/templates/all_clothes.html
{% extends 'admin.html' %}
{% block contentarea %}
{%load static%}
<script>
    document.title = "All Clothes";
</script>
<div>
    <table class="table table-striped">
        <thead>
            <tr>
                <td>Product ID</td>
                <td>Product Image</td>
                <td>Product Name</td>
                <td>Product Price</td>
                <td>Manufacturer Name</td>
                <td>Material</td>
                <td></td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            {%for cloth in clothes%}
            <tr>

                <td>{{cloth.id}}</td>
                <td><img src="/media/{{cloth.photo1}}" alt="pic" width="80px"></td>
                <td>{{cloth.name}}</td>
                <td>{{cloth.price}}</td>
                <td>{{cloth.company}}</td>
                <td>{{cloth.material}}</td>
                <td><a href="/admin/clothes/{{cloth.id}}/edit"><button class="btn btn-success">Edit</button></a></td>
                <td>
                    <form action="/admin/clothes/{{cloth.id}}/delete" method="POST">
                        {%csrf_token%}
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                </td>
            </tr>
                {%endfor%}
        </tbody>
    </table>
</div>

<script>
    document.getElementById('all_clothes').classList.add('btn-primary')
</script>
{% endblock contentarea %}

clothes/templates/clothes.html
<!DOCTYPE html>
<html lang="en">
   <head>
      {% load static %}
      <style>
         .suits{
            max-height: 700px;
            height: 500px;
         }
      </style>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>FABHUT</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}">
      <!-- style css -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'css/responsive.css'%}">
      <!-- fevicon -->
      <link rel="icon" href="{% static 'images/fevicon.png'%}" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="css/jquery.mCustomScrollbar.min.css">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <!-- fonts -->
      <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
      <!-- font awesome -->
      <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
      <!--  -->
      <!-- owl stylesheets -->
      <link href="https://fonts.googleapis.com/css?family=Great+Vibes|Poppins:400,700&display=swap&subset=latin-ext" rel="stylesheet">
      <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'%}">
      <link rel="stylesoeet" href="{% static 'css/owl.theme.default.min.css'%}">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
   </head>
   <style>
      .row{
         justify-content: center !important;
      }
   </style>
   <body>
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" id="alert-message-div">
          <strong>Hub Hut!</strong> {{message}}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
          <script>
              let timeout = 5000;
              let div = document.getElementById('alert-message-div');
              setTimeout((resp) => {
                  div.style.display = "none"
                  
              }, timeout);
          </script>
        </div>
        {% endfor %}
<!-- banner bg main start -->
<div class="banner_bg_main">
  <!-- header top section start -->
  <div class="container">
     <div class="header_section_top">
        <div class="row">
           <div class="col-sm-12">
              <div class="custom_menu">
                 <ul>
                    <li><a href="#">Best Sellers</a></li>
                    <li><a href="#">Gift Ideas</a></li>
                    <li><a href="#">New Releases</a></li>
                    <li><a href="#">Today's Deals</a></li>
                    <li><a href="#">Customer Service</a></li>
                 </ul>
              </div>
           </div>
        </div>
     </div>
  </div>
  <!-- header top section start -->
  <!-- logo section start -->
  <div class="logo_section">
     <div class="container">
        <div class="row">
           <div class="col-sm-12">
              <div class="logo"><a href="index.html"><img src="{% static 'images/logo1.png'%}"></a></div>
           </div>
        </div>
     </div>
  </div>
  <!-- logo section end -->
  <!-- header section start -->
  <div class="header_section">
     <div class="container">
        <div class="containt_main">
           <div id="mySidenav" class="sidenav">
              <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
              <a href="index.html">Home</a>
              <a href="fashion.html">Fashion</a>
              <a href="electronic.html">Electronic</a>
              <a href="jewellery.html">Jewellery</a>
              {% if request.user.is_superuser %}
              <a href="/admin">Dashbord</a>
              <a href="/admin/clothes/add">Add Clothes</a>
              <a href="/admin/clothes/new-category">Add Clothe Category</a>
              {% endif %}
           </div>
           <span class="toggle_icon" onclick="openNav()"><img src="{% static 'images/toggle-icon.png'%}"></span>
           <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">All Category 
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                 <a class="dropdown-item" href="#">Action</a>
                 <a class="dropdown-item" href="#">Another action</a>
                 <a class="dropdown-item" href="#">Something else here</a>
              </div>
           </div>
           <div class="main">
              <!-- Another variation with a button -->
              <div class="input-group">
                 <input type="text" class="form-control" placeholder="Search this blog">
                 <div class="input-group-append">
                    <button class="btn btn-secondary" type="button" style="background-color: #f26522; border-color:#f26522 ">
                    <i class="fa fa-search"></i>
                    </button>
                 </div>
              </div>
           </div>
           <div class="header_box">
              <div class="lang_box ">
                 <a href="#" title="Language" class="nav-link" data-toggle="dropdown" aria-expanded="true">
                 <img src="{% static 'images/flag-uk.png'%}" alt="flag" class="mr-2 " title="United Kingdom"> English <i class="fa fa-angle-down ml-2" aria-hidden="true"></i>
                 </a>
                 <div class="dropdown-menu ">
                    <a href="#" class="dropdown-item">
                    <img src="{% static 'images/flag-france.png'%}" class="mr-2" alt="flag">
                    French
                    </a>
                 </div>
              </div>
              <div class="login_menu">
                 <ul>
                    <li>
                       {% if request.user.is_authenticated %}
                       <a href="/customers/logout">
                          <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                          <span class="padding_10">Logout</span></a>
                          {% else %}
                          <a href="/customers/login">
                             <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                             <span class="padding_10">Login</span></a>
                             {% endif %}
                          </li>
                          <li>
                             {% if request.user.is_authenticated %}
                             {% if request.user.is_superuser %}
                             <a href="/admin/clothes/add">
                                <i class="fa fa-user" aria-hidden="true"></i>
                                <span class="padding_10">Dashboard</span></a>
                                {% else %}
                                <a href="#">
                                   <i class="fa fa-user" aria-hidden="true"></i>
                                   <span class="padding_10">Cart</span></a>
                                
                                   {% endif %}
                                   {% else %}
                             <a href="/customers/signup">
                                <i class="fa fa-user" aria-hidden="true"></i>
                                <span class="padding_10">Signup</span></a>
                                {% endif %}
                    </li>
                 </ul>
              </div>
           </div>
        </div>
     </div>
  </div>
  <!-- header section end -->
  <!-- banner section start -->
  <div class="banner_section layout_padding">
     <div class="container">
        <div id="my_slider" class="carousel slide" data-ride="carousel">
           <div class="carousel-inner">
              <div class="carousel-item active">
                 <div class="row">
                    <div class="col-sm-12">
                       <h1 class="banner_taital">Get Start <br>Your favriot shoping</h1>
                       {% if request.user.is_authenticated %}
                       <div class="buynow_bt"><a href="/suits">Explor</a></div>
                       {%else%}
                       <div class="buynow_bt"><a href="/customers/login">Login</a></div>
                       {% endif %}
                    </div>
                 </div>
              </div>
              <div class="carousel-item">
                 <div class="row">
                    <div class="col-sm-12">
                       <h1 class="banner_taital">Get Start <br>Your favriot shoping</h1>
                       {% if request.user.is_authenticated %}
                       <div class="buynow_bt"><a href="/suits">Explor</a></div>
                       {%else%}
                       <div class="buynow_bt"><a href="/customers/login">Login</a></div>
                       {% endif %}
                    </div>
                 </div>
              </div>
              <div class="carousel-item">
                 <div class="row">
                    <div class="col-sm-12">
                       <h1 class="banner_taital">Get Start <br>Your favriot shoping</h1>
                       {% if request.user.is_authenticated %}
                       <div class="buynow_bt"><a href="/suits">Explor</a></div>
                       {%else%}
                       <div class="buynow_bt"><a href="/customers/login">Login</a></div>
                       {% endif %}
                    </div>
                 </div>
              </div>
           </div>
           <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
           <i class="fa fa-angle-left"></i>
           </a>
           <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
           <i class="fa fa-angle-right"></i>
           </a>
        </div>
     </div>
  </div>
  <!-- banner section end -->
</div>
<div class="cards">
{%for cloth in clothes %}
<div class="card">
  <div class="card-header" style="background-image: url('/media/{{cloth.photo1}}'); background-size: cover; height: 30em;"></div>
  <div class="card-body">
    
  </div>
</div>

<div style="margin-top: 40px;">
  
  <div class="card" style="max-width: 300px;border:solid !important">
    <div class="card-head" style="display: flex;justify-content: center;background-color: whitesmoke;">
      <h2>{{cloth.name | upper}}</h2>
    </div>
    <div class="card-body" style="display: flex;justify-content: center;">
      <img src="/media/{{cloth.photo1}}" alt="img" style="max-width:280px">
    </div>
    <div class="card-footer" style="display: flex;justify-content: center;background-color: lightcoral; max-width: 300px;">
      <button type="button" class="btn btn-success">Buy Now</button>
      &ThickSpace;
      &ThickSpace;
      <button type="button" class="btn btn-dark">Add To Cart</button>
    </div>
  </div>
</div>

{%endfor%}
</div>

      <!-- footer section start -->
      <div class="footer_section layout_padding">
        <div class="container">
           <div class="footer_logo"><a href="index.html"><img src="images/footer-logo.png"></a></div>
           <div class="input_bt">
              <input type="text" class="mail_bt" placeholder="Your Email" name="Your Email">
              <span class="subscribe_bt" id="basic-addon2"><a href="#">Subscribe</a></span>
           </div>
           <div class="footer_menu">
              <ul>
                 <li><a href="#">Best Sellers</a></li>
                 <li><a href="#">Gift Ideas</a></li>
                 <li><a href="#">New Releases</a></li>
                 <li><a href="#">Today's Deals</a></li>
                 <li><a href="#">Customer Service</a></li>
              </ul>
           </div>
           <div class="location_main">Help Line  Number : <a href="#">+1 1800 1200 1200</a></div>
        </div>
     </div>
     <!-- footer section end -->
     <!-- copyright section start -->
     <div class="copyright_section">
        <div class="container">
           <p class="copyright_text">© 2020 All Rights Reserved. Design by <a href="https://html.design">Free html  Templates</a></p>
        </div>
     </div>
     <!-- copyright section end -->
     <!-- Javascript files-->
     <script src="{% static 'js/jquery.min.js'%}"></script>
     <script src="{% static 'js/popper.min.js'%}"></script>
     <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
     <script src="{% static 'js/jquery-3.0.0.min.js'%}"></script>
     <script src="{% static 'js/plugin.js'%}"></script>
     <!-- sidebar -->
     <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js'%}"></script>
     <script src="{% static 'js/custom.js'%}"></script>
     <script>
        function openNav() {
          document.getElementById("mySidenav").style.width = "250px";
        }
        
        function closeNav() {
          document.getElementById("mySidenav").style.width = "0";
        }
     </script>
  </body>
</html>